# Generated by Django 4.1.4 on 2022-12-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=50, verbose_name='Cell ID Code')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='LAT')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='LONG')),
                ('azimuth', models.IntegerField(null=True, verbose_name='Azimuth')),
                ('radius', models.IntegerField(null=True, verbose_name='Radius [meters]')),
                ('aperture', models.FloatField(default=60, null=True, verbose_name='Angle of aperture')),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
